### ISSUE TITLE
can not find module fs

### ISSUE THREAD

**Issue by shubhambatra** [AntuanKhanna/html-table-to-csv#2]

**Comment by AntuanKhanna** [comment]
> module fs can not be found

`fs` is a [built-in module](https://nodejs.org/api/fs.html).

@shubhambatra, to test a copy of `node` on a specific machine you can run the following Bash command. It should exit with code `0` and print nothing to `stdout`.

```sh
node --eval 'require("fs")' || node --version
```

> Solution: delete var fs = require('fs');

If you found a solution - great! In case you want to continue the discussion, you can provide more information about your use case.
